# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: Warmhut
email: support@warmhutgroup.com
twitter: https://twitter.com/warmhutGroup/
facebook: https://web.facebook.com/warmhutpr/
environment: production
description: 'We are a tech startup that help businesses broaden their markets by cultivating a strong online presence.'
baseurl: ""
url: "https://warmhutgroup.com"
disqus: 
  shortname: warmhut

# Build settings
markdown: kramdown
theme: minima
gems:
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
